### ISSUE TITLE
Tengo un problema con las ordenes de los bots

### ISSUE THREAD

**Issue by NEKpewar** [Daiivr/DaiBot.NET#1]
Hola buenas hace unas semanas utilice el bot (tu fork) y esta super bueno, me pasa lo siguiente, el bot funciona bien unos dias (aprox 2 o 3 dias, lo dejo 24 horas) y luego ya no acepta los comandos y eso que el bot esta funcionando (esta en verde el cuadrado), intente cambiar de consola ya que tengo 2 pero tengo el mismo problema, tambien cambie de juego ya que tengo los 2 juegos (escarlata y purpura) y tambien va a el mismo problema, probe con escudo y espada y no me da esas desconexiones,

Con otros bots no me pasa nada de eso.

cual crees que deberia ser el problema?

gracias por tu respuesta

**Comment by Daiivr** [comment]
Hola, muchas gracias por tu reporte, ya hemos recibido algunos mas y estamos intentado encontrar la causa y arreglar el problema...

Pregunta: Esto ocurre con todos los juegos o solo con los de la ultima generación?

**Comment by NEKpewar** [comment]
Con el de escudo y espada funciona normal, no los he probado en los otros juegos (BDSP/PLA), pueda ser problema del sysbot-base

**Comment by Daiivr** [comment]
Vale muchas gracias! En cuanto tengamos una solución publicare un nueva versión, perdona las molestias 😅

**Comment by hexbyt3** [comment]
Latest commit should help solve the issue of discord disconnecting and not being able to reconnect.

**Comment by Daiivr** [comment]
Thank You @bdawg1989! I already update my fork so it should be fixed as u said ❤️

@NEKpewar Ya debería estar arreglado, pruébalo y déjanos saber :)

**Comment by NEKpewar** [comment]
voy a probarlo por dias, comentare por aqui como me fue, si tuve alguna desconexión o no, como te dije dejo mi bot 24/7 y despues de 2 dias era que tenia esa desconfiguracion, gracias por todo

**Comment by NEKpewar** [comment]
Hola vengo a reportar, me sigue el error, ahora creo que es mas constante osea ocurre a las horas, he grabado un video donde pongo para generar el pokemon y el bot no hace la comunicacion con la consola 

https://github.com/user-attachments/assets/d7c6cf4f-051f-4897-b912-625927416bdf

Edit: Aunque no muestro bien lo que sucede al final del video (pense que habia grabado mas), literal no aceptó el comando y se quedo en "nada que comprobar....", pueden ver tambien que mas arriba tambien hay personas pidiendo y no les acepto

Hice la prueba tambien con internet porque habia leido que tal vez daba problemas con internet 5G pero ahora estoy hosteando el bot con datos 2.4Ghz e igual da el error, como digo solo es en escarlata y purpura, en escudo y espada da genial, funciona bien

**Comment by hexbyt3** [comment]
Discord apparently has messed some things up with the bots, and you will more than likely just need to create a new discord bot/application and use it instead of your old one. Try that and see how it goes.

**Comment by NEKpewar** [comment]
Ok, I will do that, thnx gengar, when I was teaching a friend to put a sysbot, I saw a few changes on developer's portal web like a "installation" option and another more, maybe it's the reason about that

**Comment by hexbyt3** [comment]
Yes, lots of new changes to discord lately. Let me know if that works for you :)

**Comment by Daiivr** [comment]
Also, if you know how to build the bot, please do so. One of the latest commits added after the last version was published is needed to fix this issue.

**Comment by NEKpewar** [comment]
@bdawg1989 Sorry I created a new bot app and the same problem, this time only took 30 min, I think maybe it's not the bot app because my sw/sh bot (with an app created long ago) would have the same problem, but doesn't it, my sw/ sh bot works perfectly and that bot I don't updated yet heheh

@Daiivr Baje la ultima version cuando lo publicastes en los "releases" pero es recomendable buildearlo (si se hacerlo) o bajarlo de los releases? 

Ahora solo lo he probado con el bot tuyo, me faltaria probarlo con el de gengar (ingles), aunque sé que es completamente igual, no estaria mas intentarlo
![image](https://github.com/user-attachments/assets/8f5a4aa1-b0d1-4943-9f04-5da9c47e1518)

**Comment by Daiivr** [comment]
@NEKpewar te recomiendo hacerle build a esta ya que nos falto agregar un ajuste al release mas reciente que ayuda con la reconeccion del bot a discord si este se desconecta, hazle build y pruebalo.

PD: Cuando salga el próximo release ya estará implementado pero por el momento debes hacerle build tu mismo.

**Comment by NEKpewar** [comment]
@Daiivr 
Listo lo buildee y lo puse a probar!!! Ojala que si funcione esta vez!!!

Otra cosa parece que en el gif cuando se prende el bot sale "stop", no se si es del bot o alguna configuracion que hice jejje

![image](https://github.com/user-attachments/assets/b9550adc-befa-4fdc-af69-2e3827e4b9a7)

**Comment by Daiivr** [comment]
Ups, luego arreglo eso xd, gracias por decirme

**Comment by NEKpewar** [comment]
Bueno se que esta cerrado el issue pero solo para agregar que ya va 1 semana y todo bien!! Gracias por arreglar ese problema
